Duration between two dates
khushi-purwar/WebDev-ProjectKart pull request #1441
Opened 2022-05-08 11:01 UTC by Kumar-Ankit56

<hr>

## Description 📜

### The idea behind this project
It's turned very tough when you have assigned with that count the total between the 1/18 to 6/28.

### How does it work

For minimizing the workload we have this alternative while loading the project we will have a text box for two dates and below the will submit button just click it you will get the actual days between two dates of the preview message. 

Fixes #1390 

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
## Screenshots / Gif (Recommended) 📸

![Screenshot (177)](https://user-images.githubusercontent.com/73521123/167266329-da17252a-12d1-458f-a3a8-296e95a0dac4.png)

https://user-images.githubusercontent.com/73521123/167266472-dc15859b-9177-4b33-b1d7-f5d34980ce35.mp4

2022-05-08 18:33 UTC, Mrjoy832 requested changes

2022-05-08 18:33 UTC, Mrjoy832 commented on Duration during two dates/Readme.md
> +**Project Description**
Wrong Project Title

2022-05-08 18:54 UTC, Kumar-Ankit56 commented on Duration during two dates/Readme.md
> +**Project Description**
Oh sorry let me fix

2022-05-08 18:57 UTC, Kumar-Ankit56 commented
@Mrjoy832 Changes done plz review it.

2022-05-09 01:17 UTC, Mrjoy832 approved these changes

2022-05-09 01:19 UTC, merged