Connect Four Game
khushi-purwar/WebDev-ProjectKart pull request #1452
Opened 2022-05-08 15:00 UTC by SarthakSKumar

<hr>

## Description 📜

Connect Four Game

Fixes #1415 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸
![image](https://user-images.githubusercontent.com/81763561/167284757-f631cab2-3104-4a96-a4a2-ac8e5bd0dc19.png)
![image](https://user-images.githubusercontent.com/81763561/167284760-6ac1c8a5-17c1-4af6-9909-e63ab054085b.png)

2022-05-09 01:31 UTC, Mrjoy832 commented on ConnectFour/README.md
> +![ConnectFour](https://user-images.githubusercontent.com/68684482/124650666-98456c00-deb7-11eb-80e7-87e999d8ab96.png)
add a working demo video

2022-05-16 16:25 UTC, SarthakSKumar commented
Shall make the required changes and update. Thanks

2022-05-18 17:37 UTC, Mrjoy832 requested changes

2022-05-18 17:37 UTC, Mrjoy832 commented on ConnectFour/README.md
> +![ConnectFour](https://user-images.githubusercontent.com/68684482/124650666-98456c00-deb7-11eb-80e7-87e999d8ab96.png)
add demo video...not SS only

2022-05-27 18:23 UTC, Mrjoy832 commented
## @SarthakSKumar finish by tomorrow either I will close

2022-06-02 11:00 UTC, gurjeetsinghvirdee approved these changes

2022-06-02 11:00 UTC, merged