Adding Profile statistic
khushi-purwar/WebDev-ProjectKart pull request #1604
Opened 2022-05-10 12:53 UTC by kalashvasaniya

Hey I made Profile statistic Project Which Is Very Good!

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript,

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

2022-05-10 12:55 UTC, kalashvasaniya commented
https://user-images.githubusercontent.com/88212870/167633138-9b5a418b-80ab-485d-a245-4796ac017a0d.mov

2022-05-16 08:34 UTC, Mrjoy832 commented
Add Readme & describe what is this in readme

2022-05-17 08:53 UTC, Mrjoy832 requested changes

2022-05-17 08:53 UTC, Mrjoy832 commented on Profile-statistics/README.md
> +### Profile-Statistics help you you find the Experience in fun way!
put it at top and **must Describe about this**

2022-05-17 14:44 UTC, merged