pay for cause
khushi-purwar/WebDev-ProjectKart pull request #1658
Opened 2022-05-12 17:48 UTC by DragonUncaged

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #1625

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project
- [] Modified or enhanced the existing projects
- [] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using only HTML & CSS
- [] Project using HTML, CSS & JS
- [] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸
![image](https://user-images.githubusercontent.com/72241207/168136497-ae182dde-3fd7-4f2e-9674-233173bcef80.png)

2022-05-17 05:37 UTC, Mrjoy832 commented
Add readme with Demo Video

2022-05-17 08:44 UTC, Mrjoy832 requested changes

2022-05-17 08:44 UTC, Mrjoy832 commented on Pay for the Cause/readme.md
> +![](https://user-images.githubusercontent.com/72241207/168136497-ae182dde-3fd7-4f2e-9674-233173bcef80.png)
add demo video as I said earlier

2022-05-17 15:51 UTC, Mrjoy832 approved these changes

2022-05-17 15:52 UTC, merged

2022-05-30 03:35 UTC, gurjeetsinghvirdee commented
Content copied from codepen https://codepen.io/gabrielsxp/pen/XMbrar

Remove labels

cc: @Mrjoy832