Final commit with all the files added , hopefullt didn't miss anything.
khushi-purwar/WebDev-ProjectKart pull request #187
Opened 2022-03-04 15:15 UTC by uhini0201

<hr>

## Description 📜

I have added my project which is a newsletter signup page, fully functional, deployed and responsive. 

Fixes #41 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

![output1](https://user-images.githubusercontent.com/59994163/156789068-c31c070b-356b-4d9d-808c-c9f15475e6ba.jpeg)
![output2](https://user-images.githubusercontent.com/59994163/156789120-f8587877-9abc-413e-ba24-8cc925a704d5.jpeg)
![output3](https://user-images.githubusercontent.com/59994163/156789142-09685e53-85bc-47b9-b9df-7a61ae09977b.jpeg)

2022-03-04 15:16 UTC, uhini0201 commented
@meinhoonharsh please review this and let me know the changes.

2022-03-04 16:59 UTC, meinhoonharsh requested changes

2022-03-04 16:59 UTC, meinhoonharsh commented on uhini_newsletter/app.js
> +        status: "subscribed",
It's a Node Application, and it does not follow the Project Tech Stacks 
So I am unable to allow this to merge

2022-03-04 18:20 UTC, uhini0201 commented
@meinhoonharsh i have asked @khushi-purwar whether I can do it or not, she said I can as it is deployed one can see the final project too. Since she allowed it, i coded it.

2022-03-06 09:26 UTC, uhini0201 commented
@meinhoonharsh ????

2022-03-06 10:14 UTC, meinhoonharsh commented
@khushi-purwar Please Look into it

2022-03-12 12:56 UTC, uhini0201 commented
@khushi-purwar can you please look into it??

2022-03-13 06:22 UTC, uhini0201 commented
@khushi-purwar Please update what else is needed to be done.
@meinhoonharsh

2022-03-13 13:37 UTC, closed without merging