Added Maze Game Project
khushi-purwar/WebDev-ProjectKart pull request #188
Opened 2022-03-04 15:32 UTC by Srishti2128

<hr>

## Description 📜

Added Maze Game Project.

Fixes #175 

The maze game works by presenting a maze in front of the user with a caterpillar that would like to feed on the cabbage but has to reach it through a maze. **The player has to navigate the caterpillar using the arrow buttons of the keyboard or using the mouse and help it reach the cabbage**. It **also works on phone screens perfectly** and the user can select the caterpillar and send it to desired location using hand touch. This game also has option to select from **various difficulty levels viz : Easy, Medium, Hard and Extreme** and with each increasing level, the user is presented with a more complex maze. Every single maze is different and unique.

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

**Easy Level :**

![Screenshot 2022-03-04 151008](https://user-images.githubusercontent.com/90510806/156745017-907031d4-e80e-4b80-9e4f-1d206914bbb1.png)

**Medium Level :**

![Screenshot 2022-03-04 151025](https://user-images.githubusercontent.com/90510806/156745061-0371d0d2-2e01-4f5d-b1d9-5b1cc905dfeb.png)

**Hard Level :**

![Screenshot 2022-03-04 151041](https://user-images.githubusercontent.com/90510806/156745125-0535741b-0b11-46fb-ab10-ef70f65f1b06.png)

**Extreme Level :**

![Screenshot 2022-03-04 151056](https://user-images.githubusercontent.com/90510806/156745162-9dac7947-3077-4f12-8c54-7bc89049a463.png)

When the user successfully completes the right path, **the number of steps taken is also printed on the screen along with a congratulations message**

![Screenshot 2022-03-04 151123](https://user-images.githubusercontent.com/90510806/156745358-33cc62b1-d6be-4ec5-8bd5-761f045a606f.png)

2022-03-04 15:33 UTC, Srishti2128 commented
Kindly review and merge the PR.

Thank You !

2022-03-04 16:37 UTC, meinhoonharsh requested changes

2022-03-04 16:37 UTC, meinhoonharsh commented on 34.Maze-Game/index.html
> +  <html lang="en-GB">
double html tag

2022-03-04 17:37 UTC, Srishti2128 commented on 34.Maze-Game/index.html
> +  <html lang="en-GB">
Have resolved the issue. Kindly verify.

2022-03-05 10:23 UTC, khushi-purwar approved these changes

2022-03-05 10:23 UTC, merged