I have uploaded all the required files in this.
khushi-purwar/WebDev-ProjectKart pull request #192
Opened 2022-03-04 15:55 UTC by deepu0201

<hr>

## Description 📜

I have added a project of mine, which is a counter page.

Fixes #42 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸
Add the screenshot of the changes you have made

![output1](https://user-images.githubusercontent.com/73191735/156796167-545bddbf-0d28-41c6-a0ce-c3d4ea72c1d9.jpeg)

2022-03-04 15:56 UTC, deepu0201 commented
@meinhoonharsh please review and let me know if anything is needed

2022-03-04 16:27 UTC, meinhoonharsh requested changes
Started looking at HTML file, found some changes 🙃

2022-03-04 18:21 UTC, uhini0201 commented on Counter/index.html
> +        <title> Uhini's Counter</title>
Okk will change that @meinhoonharsh

2022-03-04 18:25 UTC, deepu0201 commented
@meinhoonharsh updated it.

2022-03-08 02:10 UTC, khushi-purwar approved these changes

2022-03-08 02:10 UTC, merged