Added Glassmorphism #79
khushi-purwar/WebDev-ProjectKart pull request #266
Opened 2022-03-09 08:03 UTC by CoderSahil128

<hr>

## Description 📜

I am a contributor from GSSoC - 22. I have created different kinds of glassmorphism card UI designs and have added some effects like hover and tilt effects.so So kindly Review and merge my PR.

Fixes #79 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ ] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS
- [ ] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

![Demo1](https://user-images.githubusercontent.com/97339865/157397905-57f72f48-b096-403d-bf07-1d2d7cfc4f36.jpeg)
![Demo2](https://user-images.githubusercontent.com/97339865/157397920-82c53d75-29e6-4a31-bf5b-f5ff0874fbf0.jpeg)
![Demo3](https://user-images.githubusercontent.com/97339865/157397925-d8a9ad3f-b11c-4854-b87d-c2be4a55d59d.jpeg)

2022-03-09 16:28 UTC, meinhoonharsh requested changes
All things are pretty good, just requested few changes in Readme

2022-03-09 16:28 UTC, meinhoonharsh commented on Animated-Glassmorphism-Vanila-Js/README.md
> +<h3>Tech Stack</h3>
Writing Heading using `#` in Markdown would be a Good practice

2022-03-09 16:28 UTC, meinhoonharsh commented on Animated-Glassmorphism-Vanila-Js/README.md
> +![Demo3](https://raw.githubusercontent.com/CoderSahil128/WebDev-ProjectKart/master/Animated-Glassmorphism-Vanila-Js/Demo3.jpeg)
Giving Relative path in the same Repository will be a better option, If you are using Path from your Repository, then If someday you privates/delete your repository, then these Images will be no more accessible

2022-03-26 08:42 UTC, khushi-purwar commented
Kindly do the changes requested by @meinhoonharsh

2022-04-13 20:36 UTC, gurjeetsinghvirdee commented
No response from the contributor's side so I'm closing this issue

2022-04-13 20:36 UTC, closed without merging