Added Google Search Engine Clone
khushi-purwar/WebDev-ProjectKart pull request #445
Opened 2022-04-03 19:54 UTC by gurjeetsinghvirdee

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #403 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

2022-04-03 20:06 UTC, meinhoonharsh reviewed
All things are good to get merged
@khushi-purwar It is a React Application, If we are merging Applications based on stack other than core HTML, CSS and JS then this PR can be merged

2022-04-03 20:11 UTC, meinhoonharsh requested changes

2022-04-03 20:11 UTC, meinhoonharsh commented on Google-Search-Engine-Clone/.eslintcache
> +[{"E:\\GSSo'C 22\\WebDev-ProjectKart\\Google-Search-Engine-Clone\\src\\index.js":"1","E:\\GSSo'C 22\\WebDev-ProjectKart\\Google-Search-Engine-Clone\\src\\StateProvider.js":"2","E:\\GSSo'C 22\\WebDev-
`.eslintcache` just add this inside `.gitignore`

2022-04-04 02:14 UTC, khushi-purwar commented
> All things are good to get merged @khushi-purwar It is a React Application, If we are merging Applications based on stack other than core HTML, CSS and JS then this PR can be merged

Yes, we are accepting react application

2022-04-04 02:14 UTC, khushi-purwar approved these changes

2022-04-04 02:14 UTC, merged

2022-04-08 03:59 UTC, Kushal997-das commented
@khushi-purwar Please remove the tag from this PR as this PR exits in multiple repos

[repos1](https://github.com/surajm-333/Ace-The-FrontEnd/pull/103)
[repos2](https://github.com/Ayush7614/Bundli-Frontend/pull/558)
[repos3](https://github.com/Rayman-Sodhi/Clone-IT/pull/880)