Added my portfolio
khushi-purwar/WebDev-ProjectKart pull request #659
Opened 2022-04-10 12:39 UTC by NikhilMahana

<hr>

## Description 📜
#658 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

![image](https://user-images.githubusercontent.com/85444889/162618527-d7af0bee-cb40-4c2e-b3e3-cedd58a94915.png)

2022-04-12 13:26 UTC, khushi-purwar requested changes
Please add the readme file.

2022-04-12 15:40 UTC, NikhilMahana commented
@khushi-purwar Added Readme.md

2022-04-13 21:03 UTC, gurjeetsinghvirdee approved these changes
GTG

2022-04-14 05:42 UTC, khushi-purwar approved these changes

2022-04-14 05:42 UTC, merged