Added Falling Snowflakes Effect
khushi-purwar/WebDev-ProjectKart pull request #677
Opened 2022-04-11 07:38 UTC by LiQuiD-404

<hr>

## Description 📜

Added Falling Snowflakes Effect using HTML and CSS. 

Fixes #494 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using only HTML & CSS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

![snip1](https://user-images.githubusercontent.com/94376674/162687869-35db1c19-9f2a-4b7a-b812-be18dbe31f59.png)

2022-04-11 19:11 UTC, meinhoonharsh requested changes
`script.js` is not in the files 🙃

2022-04-11 19:25 UTC, LiQuiD-404 commented
@meinhoonharsh Sorry there is no Javascript in this project because it is a CSS effect.

2022-04-12 03:28 UTC, LiQuiD-404 commented
@meinhoonharsh Made the changes. Kindly review.

2022-04-12 13:04 UTC, khushi-purwar approved these changes

2022-04-12 13:04 UTC, merged