Added Speed Typer
khushi-purwar/WebDev-ProjectKart pull request #735
Opened 2022-04-12 10:37 UTC by Abh1shekSingh

<hr>

## Description 📜

Speed Typer is an efficient application to increase your typing speed. All you have to do is typer sum random words that pop on screen with in seconds of time

Fixes #733 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

![tyoing](https://user-images.githubusercontent.com/71981463/162942145-3b68506d-eb0d-45e6-ba69-70ac3c50178b.JPG)
![tyty](https://user-images.githubusercontent.com/71981463/162942153-7621104d-8bab-427c-8125-2146be39106e.JPG)

2022-04-12 13:55 UTC, khushi-purwar requested changes
Please add the readme file.

2022-04-13 02:40 UTC, Abh1shekSingh commented
@khushi-purwar I am Done with Readme File Please Review it now. @meinhoonharsh

2022-04-13 21:07 UTC, gurjeetsinghvirdee approved these changes
GTG

2022-04-14 05:43 UTC, khushi-purwar approved these changes

2022-04-14 05:43 UTC, merged